<?php

/**
 * @file
 * Code for the TPG Global.
 */

/**
 * Implements hook_node_view_alter().
 */
function tpg_global_node_view_alter(&$build) {

  // Adding read more to Linked Entity nodes.
  if ($build['#view_mode'] == 'overview') {
    $node = $build['#node'];
    $links=array();
    $links['node-readmore'] = array(
      'title' => t('> read more'),
      'href' => 'node/' . $node->nid,
      'html' => TRUE,
      'attributes' => array('rel' => 'tag', 'class' => array('entity-read-more')),
    );
    // Assign links
    $build['links']['node']['#links']=$links;
  }
}

/**
 * Implements hook_views_query_alter().
 */
function tpg_global_views_query_alter(&$view, &$query) {
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tpg_global_form_paragraphs_page_node_form_alter(&$form, &$form_state, $form_id) {
  // Adding range of weights.
  $range = array();
  for ($i = -20; $i <= 20; ++$i) {
    $range[$i] = $i;
  }
  $form['field_homepage_weight']['und']['#options'] = $range;
  $form['field_homepage_weight']['und']['#default_value'] = 0;
}

