<?php
/**
 * @file
 * tpg_artist_and_prints.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function tpg_artist_and_prints_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-artist-field_paragraphs_content'.
  $field_instances['node-artist-field_paragraphs_content'] = array(
    'bundle' => 'artist',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_paragraphs_content',
    'label' => 'Paragraphs Content',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'select',
      'allowed_bundles' => array(
        '2_column_image_left_image_right' => '2_column_image_left_image_right',
        '2_column_image_left_no_image' => '2_column_image_left_no_image',
        '2_column_left_text_only' => '2_column_left_text_only',
        '2_column_text_left_image_right' => '2_column_text_left_image_right',
        '3_column_text_left_image_right' => '3_column_text_left_image_right',
        'attachments' => 'attachments',
        'block_quote' => 'block_quote',
        'bulleted_list' => 'bulleted_list',
        'button' => 'button',
        'embed_video' => 'embed_video',
        'full_width_image_caption' => -1,
        'full_width_image_caption_content' => 'full_width_image_caption_content',
        'full_width_video_header' => -1,
        'header_gallery' => -1,
        'header_image_left_image_right' => -1,
        'header_image_lightbox' => -1,
        'image_left_2_3_width' => 'image_left_2_3_width',
        'image_left_text_right' => 'image_left_text_right',
        'image_reading_width_colorbox' => 'image_reading_width_colorbox',
        'reading_width_image_caption' => 'reading_width_image_caption',
        'reading_width_maps' => 'reading_width_maps',
        'reading_width_webform' => 'reading_width_webform',
        'related_activities' => -1,
        'social_media_links' => 'social_media_links',
        'text_reading_width' => 'text_reading_width',
        'title_section' => 'title_section',
      ),
      'bundle_weights' => array(
        '2_column_image_left_image_right' => 2,
        '2_column_image_left_no_image' => 3,
        '2_column_left_text_only' => 4,
        '2_column_text_left_image_right' => 5,
        '3_column_text_left_image_right' => 6,
        'attachments' => 7,
        'block_quote' => 8,
        'bulleted_list' => 9,
        'button' => 10,
        'embed_video' => 11,
        'full_width_image_caption' => 12,
        'full_width_image_caption_content' => 13,
        'full_width_video_header' => 14,
        'header_gallery' => 15,
        'header_image_left_image_right' => 16,
        'header_image_lightbox' => 17,
        'image_left_2_3_width' => 18,
        'image_left_text_right' => 19,
        'image_reading_width_colorbox' => 20,
        'reading_width_image_caption' => 21,
        'reading_width_maps' => 22,
        'reading_width_webform' => 23,
        'related_activities' => 24,
        'social_media_links' => 25,
        'text_reading_width' => 26,
        'title_section' => 27,
      ),
      'default_edit_mode' => 'closed',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 45,
    ),
  );

  // Exported field_instance: 'node-artist-field_paragraphs_header_section'.
  $field_instances['node-artist-field_paragraphs_header_section'] = array(
    'bundle' => 'artist',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_paragraphs_header_section',
    'label' => 'Paragraphs Header Section',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'select',
      'allowed_bundles' => array(
        '2_column_image_left_image_right' => -1,
        '2_column_image_left_no_image' => -1,
        '2_column_left_text_only' => -1,
        '2_column_text_left_image_right' => -1,
        '3_column_text_left_image_right' => -1,
        'attachments' => -1,
        'block_quote' => -1,
        'bulleted_list' => -1,
        'button' => -1,
        'embed_video' => -1,
        'full_width_image_caption' => 'full_width_image_caption',
        'full_width_image_caption_content' => -1,
        'full_width_video_header' => 'full_width_video_header',
        'header_gallery' => -1,
        'header_image_left_image_right' => 'header_image_left_image_right',
        'header_image_lightbox' => 'header_image_lightbox',
        'image_left_2_3_width' => -1,
        'image_left_text_right' => -1,
        'image_reading_width_colorbox' => -1,
        'reading_width_image_caption' => -1,
        'reading_width_maps' => -1,
        'reading_width_webform' => -1,
        'related_activities' => -1,
        'social_media_links' => -1,
        'text_reading_width' => -1,
        'title_section' => -1,
      ),
      'bundle_weights' => array(
        '2_column_image_left_image_right' => 2,
        '2_column_image_left_no_image' => 3,
        '2_column_left_text_only' => 4,
        '2_column_text_left_image_right' => 5,
        '3_column_text_left_image_right' => 6,
        'attachments' => 7,
        'block_quote' => 8,
        'bulleted_list' => 9,
        'button' => 10,
        'embed_video' => 11,
        'full_width_image_caption' => 12,
        'full_width_image_caption_content' => 13,
        'full_width_video_header' => 14,
        'header_gallery' => 15,
        'header_image_left_image_right' => 16,
        'header_image_lightbox' => 17,
        'image_left_2_3_width' => 18,
        'image_left_text_right' => 19,
        'image_reading_width_colorbox' => 20,
        'reading_width_image_caption' => 21,
        'reading_width_maps' => 22,
        'reading_width_webform' => 23,
        'related_activities' => 24,
        'social_media_links' => 25,
        'text_reading_width' => 26,
        'title_section' => 27,
      ),
      'default_edit_mode' => 'closed',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 43,
    ),
  );

  // Exported field_instance: 'node-artist-field_related_artist'.
  $field_instances['node-artist-field_related_artist'] = array(
    'bundle' => 'artist',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_related_artist',
    'label' => 'Related Artist',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'apply_chosen' => '',
        'fields' => array(),
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
        'type_settings' => array(
          'allow_clone' => 0,
          'allow_existing' => 1,
          'allow_new' => 0,
          'delete_references' => 0,
          'label_plural' => 'nodes',
          'label_singular' => 'node',
          'match_operator' => 'CONTAINS',
          'override_labels' => 0,
        ),
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 46,
    ),
  );

  // Exported field_instance: 'node-artist-title_field'.
  $field_instances['node-artist-title_field'] = array(
    'bundle' => 'artist',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'title_field',
    'label' => 'Title',
    'required' => TRUE,
    'settings' => array(
      'hide_label' => array(
        'entity' => 'entity',
        'page' => 0,
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => -5,
    ),
  );

  // Exported field_instance: 'node-prints-field_paragraphs_content'.
  $field_instances['node-prints-field_paragraphs_content'] = array(
    'bundle' => 'prints',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_paragraphs_content',
    'label' => 'Paragraphs Content',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'select',
      'allowed_bundles' => array(
        '2_column_image_left_image_right' => '2_column_image_left_image_right',
        '2_column_image_left_no_image' => '2_column_image_left_no_image',
        '2_column_left_text_only' => '2_column_left_text_only',
        '2_column_text_left_image_right' => '2_column_text_left_image_right',
        '3_column_text_left_image_right' => '3_column_text_left_image_right',
        'attachments' => 'attachments',
        'block_quote' => 'block_quote',
        'bulleted_list' => 'bulleted_list',
        'button' => 'button',
        'embed_video' => 'embed_video',
        'full_width_image_caption' => -1,
        'full_width_image_caption_content' => 'full_width_image_caption_content',
        'full_width_video_header' => -1,
        'header_gallery' => -1,
        'header_image_left_image_right' => -1,
        'header_image_lightbox' => -1,
        'image_left_2_3_width' => 'image_left_2_3_width',
        'image_left_text_right' => 'image_left_text_right',
        'image_reading_width_colorbox' => 'image_reading_width_colorbox',
        'reading_width_image_caption' => 'reading_width_image_caption',
        'reading_width_maps' => 'reading_width_maps',
        'reading_width_webform' => 'reading_width_webform',
        'related_activities' => -1,
        'social_media_links' => 'social_media_links',
        'text_reading_width' => 'text_reading_width',
        'title_section' => 'title_section',
      ),
      'bundle_weights' => array(
        '2_column_image_left_image_right' => 2,
        '2_column_image_left_no_image' => 3,
        '2_column_left_text_only' => 4,
        '2_column_text_left_image_right' => 5,
        '3_column_text_left_image_right' => 6,
        'attachments' => 7,
        'block_quote' => 8,
        'bulleted_list' => 9,
        'button' => 10,
        'embed_video' => 11,
        'full_width_image_caption' => 12,
        'full_width_image_caption_content' => 13,
        'full_width_video_header' => 14,
        'header_gallery' => 15,
        'header_image_left_image_right' => 16,
        'header_image_lightbox' => 17,
        'image_left_2_3_width' => 18,
        'image_left_text_right' => 19,
        'image_reading_width_colorbox' => 20,
        'reading_width_image_caption' => 21,
        'reading_width_maps' => 22,
        'reading_width_webform' => 23,
        'related_activities' => 24,
        'social_media_links' => 25,
        'text_reading_width' => 26,
        'title_section' => 27,
      ),
      'default_edit_mode' => 'closed',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-prints-field_paragraphs_header_section'.
  $field_instances['node-prints-field_paragraphs_header_section'] = array(
    'bundle' => 'prints',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_paragraphs_header_section',
    'label' => 'Paragraphs Header Section',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'select',
      'allowed_bundles' => array(
        '2_column_image_left_image_right' => -1,
        '2_column_image_left_no_image' => -1,
        '2_column_left_text_only' => -1,
        '2_column_text_left_image_right' => -1,
        '3_column_text_left_image_right' => -1,
        'attachments' => -1,
        'block_quote' => -1,
        'bulleted_list' => -1,
        'button' => -1,
        'embed_video' => -1,
        'full_width_image_caption' => -1,
        'full_width_image_caption_content' => -1,
        'full_width_video_header' => -1,
        'header_gallery' => -1,
        'header_image_left_image_right' => -1,
        'header_image_lightbox' => 'header_image_lightbox',
        'image_left_2_3_width' => -1,
        'image_left_text_right' => -1,
        'image_reading_width_colorbox' => -1,
        'reading_width_image_caption' => -1,
        'reading_width_maps' => -1,
        'reading_width_webform' => -1,
        'related_activities' => -1,
        'social_media_links' => -1,
        'text_reading_width' => -1,
        'title_section' => -1,
      ),
      'bundle_weights' => array(
        '2_column_image_left_image_right' => 2,
        '2_column_image_left_no_image' => 3,
        '2_column_left_text_only' => 4,
        '2_column_text_left_image_right' => 5,
        '3_column_text_left_image_right' => 6,
        'attachments' => 7,
        'block_quote' => 8,
        'bulleted_list' => 9,
        'button' => 10,
        'embed_video' => 11,
        'full_width_image_caption' => 12,
        'full_width_image_caption_content' => 13,
        'full_width_video_header' => 14,
        'header_gallery' => 15,
        'header_image_left_image_right' => 16,
        'header_image_lightbox' => 17,
        'image_left_2_3_width' => 18,
        'image_left_text_right' => 19,
        'image_reading_width_colorbox' => 20,
        'reading_width_image_caption' => 21,
        'reading_width_maps' => 22,
        'reading_width_webform' => 23,
        'related_activities' => 24,
        'social_media_links' => 25,
        'text_reading_width' => 26,
        'title_section' => 27,
      ),
      'default_edit_mode' => 'closed',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-prints-field_print_artist'.
  $field_instances['node-prints-field_print_artist'] = array(
    'bundle' => 'prints',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_print_artist',
    'label' => 'Print Artist',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'fields' => array(),
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
        'type_settings' => array(
          'allow_clone' => 1,
          'allow_existing' => FALSE,
          'allow_new' => 0,
          'delete_references' => 0,
          'label_plural' => 'nodes',
          'label_singular' => 'node',
          'match_operator' => 'CONTAINS',
          'override_labels' => 0,
        ),
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 10,
    ),
  );

  // Exported field_instance: 'node-prints-field_print_b_w_or_colour'.
  $field_instances['node-prints-field_print_b_w_or_colour'] = array(
    'bundle' => 'prints',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_print_b_w_or_colour',
    'label' => 'B&W or Colour',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'taxonomy',
      'settings' => array(
        'apply_chosen' => '',
        'autocomplete_path' => 'taxonomy/autocomplete',
        'size' => 60,
      ),
      'type' => 'taxonomy_autocomplete',
      'weight' => 13,
    ),
  );

  // Exported field_instance: 'node-prints-field_print_collections'.
  $field_instances['node-prints-field_print_collections'] = array(
    'bundle' => 'prints',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_print_collections',
    'label' => 'Print Collections',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'taxonomy',
      'settings' => array(
        'autocomplete_path' => 'taxonomy/autocomplete',
        'size' => 60,
      ),
      'type' => 'taxonomy_autocomplete',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'node-prints-field_print_genre'.
  $field_instances['node-prints-field_print_genre'] = array(
    'bundle' => 'prints',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_print_genre',
    'label' => 'Genre',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'taxonomy',
      'settings' => array(
        'apply_chosen' => '',
        'autocomplete_path' => 'taxonomy/autocomplete',
        'size' => 60,
      ),
      'type' => 'taxonomy_autocomplete',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'node-prints-field_print_period'.
  $field_instances['node-prints-field_print_period'] = array(
    'bundle' => 'prints',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_print_period',
    'label' => 'Period',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'taxonomy',
      'settings' => array(
        'apply_chosen' => '',
        'autocomplete_path' => 'taxonomy/autocomplete',
        'size' => 60,
      ),
      'type' => 'taxonomy_autocomplete',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'node-prints-title_field'.
  $field_instances['node-prints-title_field'] = array(
    'bundle' => 'prints',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'title_field',
    'label' => 'Title',
    'required' => TRUE,
    'settings' => array(
      'hide_label' => array(
        'entity' => 'entity',
        'page' => 0,
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('B&W or Colour');
  t('Genre');
  t('Paragraphs Content');
  t('Paragraphs Header Section');
  t('Period');
  t('Print Artist');
  t('Print Collections');
  t('Related Artist');
  t('Title');

  return $field_instances;
}
