<?php

/**
 * implement hook_watchdog().
 */
function log2u_watchdog(array $log_entry) {
  $log_severities = _log2u_get_log_severity();
  $log_types = _log2u_get_log_type();
  if(in_array($log_entry['severity'], $log_severities)&&in_array($log_entry['type'], $log_types)){
    _log2u_curl_post($log_entry['user']->name, $log_entry['message'], $log_entry['severity']);
  }
}

function _log2u_curl_post($user, $message, $severity) {
  //API Url
  $url = variable_get('bam_notification_url', '');
   
  //Initiate cURL.
  $ch = curl_init($url);
  
  global $base_url;
   
  //The JSON data.
  $jsonData = array(
    'color' => "red",
    "message" => "Site: ".$base_url." ".$message,
    "notify" => 'true',
    "message_format" => "text"
  );
   
  //Encode the array into JSON.
  $jsonDataEncoded = json_encode($jsonData);
   
  //Tell cURL that we want to send a POST request.
  curl_setopt($ch, CURLOPT_POST, 1);
   
  //Attach our encoded JSON string to the POST fields.
  curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);
   
  //Set the content type to application/json
  curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json')); 
   
  //Execute the request
  $result = curl_exec($ch);
}

function _log2u_get_log_severity() {
  $result = array(
    '0',
    '1',
    '2',
    '3'
  );
  return $result;
}

function _log2u_get_log_type() {
  $result = array(
    'backup_migrate'
  );
  return $result;
}
