<?php
class CRM_VariableMembership_GracePeriodMembershipTypes {
  const CORPORATE_BENEFACTOR = 26;
  const CORPORATE_MEMBER = 27;

  const TPG_CONTEMPORARIES = 23;
  const TPG_CONTEMPORARIES_ANNUAL_DD = 24;
  const TPG_CONTEMPORARIES_MONTHLY_DD = 25;
  const CONTEMPORARIES = 50;
  const CONTEMPORARIES_ANNUAL_DD = 51;
  const CONTEMPORARIES_MONTHLY_DD = 52;
  const CONTEMPORARIES_DISCOUNTED = 20;
  const CONTEMPORARIES_DISCOUNTED_ANNUAL_DD = 22;
  const CONTEMPORARIES_DISCOUNTED_MONTHLY_DD = 21;

  const PATRON = 10;
  const PATRON_ANNUAL_DD = 9;
  const PATRON_MONTHLY_DD = 8;
  const COUNCIL = 53;
  const COUNCIL_DIRECT_DEBIT = 54;
  const COUNCIL_DIRECT_DEBIT_MONTHLY = 55;

  const CONTEMPORARY_ADVISORY__COMMITTEE = 56;
  const CONTEMPORARY_ADVISORY_COMMITTEE_ANNUAL_DD = 57;
  const CONTEMPORARY_ADVISORY_OMMITTEE_MONTHLY_DD = 58;
  const CONTEMPORARY_HONORARY_COMMITTEE = 59;
  const CONTEMPORARY_HONORARY_AMBASSADOR = 60;

  const DIRECTORS_CIRCLE_1617 = 16;
  const DIRECTORS_CIRCLE_1617_DIRECT_DEBIT = 15;
  const DIRECTORS_CIRCLE_1617_DIRECT_DEBIT_MONTHLY = 14;

  const TPG_COUNCIL = 19;
  const TPG_COUNCIL_DIRECT_DEBIT = 18;

  const ADVISORY_TPGC_COMMITTEE = 28;
  const ADVISORY_TPGC_COMMITTEE_ANNUAL_DD = 29;
  const ADVISORY_TPGC_COMMITTEE_MONTHLY_DD = 30;
  const HONORARY_TPGC_COMMITTEE = 31;
  const HONORARY_TPGC_AMBASSADOR = 32;
  const HONORARY_TPGC_PATRON = 35;

  const LIFE_PATRON = 33;
  const HONORARY_PATRON = 34;

  const PATRON_ARCHIVED = 39;
  const CONTEMPORARIES_ARCHIVED = 40;

  const DIRECTORS_CIRCLE = 47;
  const DIRECTORS_CIRCLE_DIRECT_DEBIT = 48;
  const DIRECTORS_CIRCLE_DIRECT_DEBIT_MONTHLY = 49;
}
