<?php
class CRM_VariableMembership_GracePeriodMembershipTypes {
  const CONTEMPORARIES = 20;
  const CONTEMPORARIES_ANNUAL_DD = 22;
  const CONTEMPORARIES_MONTHLY_DD = 21;
  const CONTEMPORARIES_DISCOUNTED = 23;
  const CONTEMPORARIES_DISCOUNTED_ANNUAL_DD = 24;
  const CONTEMPORARIES_DISCOUNTED_MONTHLY_DD = 25;

  const PATRON = 10;
  const PATRON_ANNUAL_DD = 9;
  const PATRON_MONTHLY_DD = 8;
  const DIRECTORS_CIRCLE_1617 = 16;
  const DIRECTORS_CIRCLE_1617_DIRECT_DEBIT = 15;
  const DIRECTORS_CIRCLE_1617_DIRECT_DEBIT_MONTHLY = 14;
  const TPG_COUNCIL = 19;
  const TPG_COUNCIL_DIRECT_DEBIT = 18;
  const TPG_COUNCIL_DIRECT_DEBIT_MONTHLY = 50;

  const ADVISORY_TPGC_COMMITTEE = 28;
  const ADVISORY_TPGC_COMMITTEE_ANNUAL_DD = 29;
  const ADVISORY_TPGC_COMMITTEE_MONTHLY_DD = 30;
  const HONORARY_TPGC_COMMITTEE = 31;
  const HONORARY_TPGC_AMBASSADOR = 32;
  const HONORARY_TPGC_PATRON = 35;

  const DIRECTORS_CIRCLE = 47;
  const DIRECTORS_CIRCLE_DIRECT_DEBIT = 48;
  const DIRECTORS_CIRCLE_DIRECT_DEBIT_MONTHLY = 49;
}
